name: Deploy Python app to Azure Web App - FoodAi using Publish Profile

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip app (excluding venv)
        run: zip -r app.zip . -x "venv/*"

      - name: Deploy to Azure using Publish Profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FoodAi'  # تأكد من الاسم
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: app.zip
